# ROUNDED CORNERS
corner-radius = 15

# BLURRING
# methods: none, gaussian, box, kernel (define custom kernel), dual_kawase
blur:
{
  method = "dual_kawase";
  size = 1;
  strength = 2;
};

# semi-transparent
blur-background = false;
blur-background-frame = false;
# Use fixed blur strength rather than adjusting according to window opacity.
blur-background-fixed = false;

# SHADOWS
shadow = true; 
shadow-radius = 1; 
shadow-opacity = 0.6;
shadow-offset-x = 0;
shadow-offset-y = 0;

# shadow-color = "#000000"
shadow-color = "#393943" # this could be set with a pywal template instead
# shadow-exclude = [];

# OTHER SETTINGS
dbus = false;
daemon = false;

# backends: `xrender`, `glx`, `egl` or `xr_glx_hybrid`
backend = "glx";
dithered-present = false;
vsync = true;
#mark-wmwin-focused = false;
#mark-ovredir-focused = false;
detect-rounded-corners = true;
detect-client-opacity = true;
use-ewmh-active-win = false;
detect-transient = true;
glx-no-stencil = true;
use-damage = true;
log-level = "warn";
#focus-exclude = "x = 0 && y = 0 && override_redirect = true";

# WINDDOW RULES
rules: (
#  { match = "class_g = 'URxvt' && focused"; opacity = 0.95; },
#  { match = "(class_g = 'URxvt' || class_g = 'st')" " && !focused"; opacity = 0.5; },
  { match = "focused"; opacity = 0.95; },
  { match = "!focused"; opacity = 0.7; },
  { match = "name = 'dwm'"; opacity = 0.1; },
  { match = "name = 'arch-desk - Moonlight' && focused"; opacity = 1; corner-radius = 0; },
  { match = "class_g = 'mpv' && focused"; opacity = 1; },
#  { match = "name = 'st' && focused"; opacity = 0.95; },
#  { match = "class_g = 'discord' && focused"; opacity = 0.95; },
#  { match = "class_g = 'TelegramDesktop' && focused"; opacity = 0.95; },
#  { match = "class_g = 'Brave-browser' && focused"; opacity = 0.95; },
#YOUTUBE
  { match = "class_i = 'crx_agimnkijcaahngcdmfeangaknmldooml' && focused"; opacity = 1; },
#TWITCH
  { match = "class_i = 'crx_comkdlimbkhemidbbpchhepidbmjpnhh' && focused"; opacity = 1; },
#TIKTOK
  { match = "class_i = 'crx_nlalbmkafgmoifbeooblidblkmlhhpnc' && focused"; opacity = 1; },
#SHADOWZ (chromium)
  { match = "class_i = 'crx_mlmocijholhcaephlliheljphhgkoopl' && focused"; opacity = 1; },
## arch-desk specifics ##
# { match = "class_g = 'steam' && focused"; opacity = 1; },
# { match = "class_g = 'steam_app_3870690' && focused"; opacity = 1; corner-radius = 0; },
########################
);


#################################
#             Fading            #
#################################
# Fade windows in/out on open/close and opacity changes.
# Default: false
fading = true;

# Opacity increase per step while fading in.
# Range: 0.01 - 1.0, default: 0.028
fade-in-step = 0.03;

# Opacity decrease per step while fading out.
# Range: 0.01 - 1.0, default: 0.03
fade-out-step = 0.03;

# If needed, time between fade steps in ms (default 10):
fade-delta = 10;

#################################
#           Animations          #
#################################
animations = (
  {
    triggers = ["close", "hide"];
    preset = "disappear";
    duration = 0.5;
    scale = 1.0;
  },
  {
    triggers = ["open", "show"];
    preset = "appear";
    duration = 0.5;
    scale = 1.0;
  },
  {
    triggers = ["geometry"]
    scale-x = {
      curve = "cubic-bezier(0,0,0,1.28)";
      duration = 0.5;
      start = "window-width-before / window-width";
      end = 1;
    }
    scale-y = {
      curve = "cubic-bezier(0,0,0,1.28)";
      duration = 0.5;
      start = "window-height-before / window-height";
      end = 1;
    }
    offset-x = {
      curve = "cubic-bezier(0,0,0,1.28)";
      duration = 0.5;
      start = "window-x-before - window-x";
      end = 0;
    }
    offset-y = {
      curve = "cubic-bezier(0,0,0,1.28)";
      duration = 0.5;
      start = "window-y-before - window-y";
      end = 0;
    }
    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
  }
);
